# Generated by Django 4.2.10 on 2024-08-16 15:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_balance_balance_created_balance_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=250, null=True, validators=[users.models.validate_non_negative]),
        ),
    ]
