# Generated by Django 4.2.10 on 2024-08-16 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ManyToManyField(related_name='courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
