# Generated by Django 4.2.10 on 2024-08-16 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_group_course_group_participants_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ManyToManyField(related_name='courses', to='courses.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ пользователя к курсу',
                'verbose_name_plural': 'Доступы пользователей к курсам',
                'ordering': ('-id',),
                'unique_together': {('user', 'course')},
            },
        ),
    ]
