# Generated by Django 4.2.10 on 2024-08-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_cost_alter_course_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cost',
            new_name='price',
        ),
    ]
